version: "3.5"

services:
  app:
    build: .
    volumes:
      - ./blog:/app/blog
      - ./wsgi.py:/app/wsgi.py
      - ./migrations:/app/migrations
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@pg:5432/blog
      CONFIG_NAME: DevConfig
      DATABASE_URL: postgresql://user:password@pg:5432/blog
      FLASK_ADMIN_SWATCH: 'cosmo'
      OPENAPI_URL_PREFIX: '/api/swagger'
      OPENAPI_SWAGGER_UI_PATH: '/'
      OPENAPI_SWAGGER_UI_VERSION: '3.22.0'
    ports:
      - 5000:5000
    depends_on:
      - pg

  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      -  ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
      